package jobsources;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class StringToolsTest {

    @Test
    public void removeEverythingBeforeTest()
    {
        String blah = "View All num of num Close (Esc) Entry Level - Software Engineer I 3.9 Relevante – San Carlos, CA 5 days ago Applied 3/15/19 Apply on Company Site Save 5 days ago Hot 57 people are looking at this job. Apply now. Job Salary: $ 90,000 We have partnered with a large Security Software Company in the San Carlos, CA area to provide them with a Entry Level Software Engineer. Please review the below description and if you are interested please contact: Asma Munir at amunir@relevante.com 484-403-4175 Major Responsibilities Develop software for the client's Security Appliances, hardware and software acceleration. Design, implementation, and support of the client's multi-core packet forwarding engine. Support customer critical issues and ongoing firewall releases. Desired Background Must have U.S Citizenship or G.C Holder Computer Science degree 0-2 years of software development experience MUST NOT HAVE MORE THAN 2 YEARS OF EXPERIENCE Internship experience preferred Knowledge in TCP/IP and Networking Operating systems: Linux, UNIX knowledge in encoding & security preferred knowledge in Linux Kernel Network Stack preferred knowledge of C/C++ Join our Talent Network - https://relevante.jobs.net/en-US/join #ZR About Relevante, Inc. – the Recruiting Firm Representing the Client for this Job Relevante is an accounting & technology direct hire recruiting and contract staffing firm. We help our Clients identify and recruit the best talent in the market and help our candidates win engaging and enriching jobs. Our Clients are some of the best companies to work for among F1000 and emerging fast growth companies in the region. Relevante has been consistently ranked as a fast growth company and one of the largest recruiting, accounting, and management consulting firms in the Philadelphia region. To stay connected with our network, please join one of our groups on LinkedIn http://www.linkedin.com/groups?mostPopular=&gid=2901 Get alerts to jobs like this, to your inbox. Create Job Alert Similar Jobs You May Like See More JobsSee All Suggested searches";
        StringTools stringTools = new StringTools();
        String actual = stringTools.removeEverythingBefore(blah,"Entry Level");
        String expected = "Entry Level - Software Engineer I 3.9 Relevante – San Carlos, CA 5 days ago Applied 3/15/19 Apply on Company Site Save 5 days ago Hot 57 people are looking at this job. Apply now. Job Salary: $ 90,000 We have partnered with a large Security Software Company in the San Carlos, CA area to provide them with a Entry Level Software Engineer. Please review the below description and if you are interested please contact: Asma Munir at amunir@relevante.com 484-403-4175 Major Responsibilities Develop software for the client's Security Appliances, hardware and software acceleration. Design, implementation, and support of the client's multi-core packet forwarding engine. Support customer critical issues and ongoing firewall releases. Desired Background Must have U.S Citizenship or G.C Holder Computer Science degree 0-2 years of software development experience MUST NOT HAVE MORE THAN 2 YEARS OF EXPERIENCE Internship experience preferred Knowledge in TCP/IP and Networking Operating systems: Linux, UNIX knowledge in encoding & security preferred knowledge in Linux Kernel Network Stack preferred knowledge of C/C++ Join our Talent Network - https://relevante.jobs.net/en-US/join #ZR About Relevante, Inc. – the Recruiting Firm Representing the Client for this Job Relevante is an accounting & technology direct hire recruiting and contract staffing firm. We help our Clients identify and recruit the best talent in the market and help our candidates win engaging and enriching jobs. Our Clients are some of the best companies to work for among F1000 and emerging fast growth companies in the region. Relevante has been consistently ranked as a fast growth company and one of the largest recruiting, accounting, and management consulting firms in the Philadelphia region. To stay connected with our network, please join one of our groups on LinkedIn http://www.linkedin.com/groups?mostPopular=&gid=2901 Get alerts to jobs like this, to your inbox. Create Job Alert Similar Jobs You May Like See More JobsSee All Suggested searches";
        assertEquals(expected, actual);
    }

    @Test
    public void removeEverythingBeforeAndTerm()
    {
        String blah = "View All num of num Close (Esc) Entry Level - Software Engineer I 3.9 Relevante – San Carlos, CA 5 days ago Applied 3/15/19 Apply on Company Site Save 5 days ago Hot 57 people are looking at this job. Apply now. Job Salary: $ 90,000 We have partnered with a large Security Software Company in the San Carlos, CA area to provide them with a Entry Level Software Engineer. Please review the below description and if you are interested please contact: Asma Munir at amunir@relevante.com 484-403-4175 Major Responsibilities Develop software for the client's Security Appliances, hardware and software acceleration. Design, implementation, and support of the client's multi-core packet forwarding engine. Support customer critical issues and ongoing firewall releases. Desired Background Must have U.S Citizenship or G.C Holder Computer Science degree 0-2 years of software development experience MUST NOT HAVE MORE THAN 2 YEARS OF EXPERIENCE Internship experience preferred Knowledge in TCP/IP and Networking Operating systems: Linux, UNIX knowledge in encoding & security preferred knowledge in Linux Kernel Network Stack preferred knowledge of C/C++ Join our Talent Network - https://relevante.jobs.net/en-US/join #ZR About Relevante, Inc. – the Recruiting Firm Representing the Client for this Job Relevante is an accounting & technology direct hire recruiting and contract staffing firm. We help our Clients identify and recruit the best talent in the market and help our candidates win engaging and enriching jobs. Our Clients are some of the best companies to work for among F1000 and emerging fast growth companies in the region. Relevante has been consistently ranked as a fast growth company and one of the largest recruiting, accounting, and management consulting firms in the Philadelphia region. To stay connected with our network, please join one of our groups on LinkedIn http://www.linkedin.com/groups?mostPopular=&gid=2901 Get alerts to jobs like this, to your inbox. Create Job Alert Similar Jobs You May Like See More JobsSee All Suggested searches";
        StringTools stringTools = new StringTools();
        String actual = stringTools.removeEverythingBeforeAndIncludingTerm(blah,"Save ");
        String expect = "5 days ago Hot 57 people are looking at this job. Apply now. Job Salary: $ 90,000 We have partnered with a large Security Software Company in the San Carlos, CA area to provide them with a Entry Level Software Engineer. Please review the below description and if you are interested please contact: Asma Munir at amunir@relevante.com 484-403-4175 Major Responsibilities Develop software for the client's Security Appliances, hardware and software acceleration. Design, implementation, and support of the client's multi-core packet forwarding engine. Support customer critical issues and ongoing firewall releases. Desired Background Must have U.S Citizenship or G.C Holder Computer Science degree 0-2 years of software development experience MUST NOT HAVE MORE THAN 2 YEARS OF EXPERIENCE Internship experience preferred Knowledge in TCP/IP and Networking Operating systems: Linux, UNIX knowledge in encoding & security preferred knowledge in Linux Kernel Network Stack preferred knowledge of C/C++ Join our Talent Network - https://relevante.jobs.net/en-US/join #ZR About Relevante, Inc. – the Recruiting Firm Representing the Client for this Job Relevante is an accounting & technology direct hire recruiting and contract staffing firm. We help our Clients identify and recruit the best talent in the market and help our candidates win engaging and enriching jobs. Our Clients are some of the best companies to work for among F1000 and emerging fast growth companies in the region. Relevante has been consistently ranked as a fast growth company and one of the largest recruiting, accounting, and management consulting firms in the Philadelphia region. To stay connected with our network, please join one of our groups on LinkedIn http://www.linkedin.com/groups?mostPopular=&gid=2901 Get alerts to jobs like this, to your inbox. Create Job Alert Similar Jobs You May Like See More JobsSee All Suggested searches";
        assertEquals(expect,actual);
    }

    @Test
    public void removeEverythingAfterTest(){
        String string = "View All num of num Close (Esc) Entry Level - Software Engineer I 3.9 Relevante – San Carlos, CA 5 days ago Applied 3/15/19 Apply on Company Site Save 5 days ago Hot 57 people are looking at this job. Apply now. Job Salary: $ 90,000 We have partnered with a large Security Software Company in the San Carlos, CA area to provide them with a Entry Level Software Engineer. Please review the below description and if you are interested please contact: Asma Munir at amunir@relevante.com 484-403-4175 Major Responsibilities Develop software for the client's Security Appliances, hardware and software acceleration. Design, implementation, and support of the client's multi-core packet forwarding engine. Support customer critical issues and ongoing firewall releases. Desired Background Must have U.S Citizenship or G.C Holder Computer Science degree 0-2 years of software development experience MUST NOT HAVE MORE THAN 2 YEARS OF EXPERIENCE Internship experience preferred Knowledge in TCP/IP and Networking Operating systems: Linux, UNIX knowledge in encoding & security preferred knowledge in Linux Kernel Network Stack preferred knowledge of C/C++ Join our Talent Network - https://relevante.jobs.net/en-US/join #ZR About Relevante, Inc. – the Recruiting Firm Representing the Client for this Job Relevante is an accounting & technology direct hire recruiting and contract staffing firm. We help our Clients identify and recruit the best talent in the market and help our candidates win engaging and enriching jobs. Our Clients are some of the best companies to work for among F1000 and emerging fast growth companies in the region. Relevante has been consistently ranked as a fast growth company and one of the largest recruiting, accounting, and management consulting firms in the Philadelphia region. To stay connected with our network, please join one of our groups on LinkedIn http://www.linkedin.com/groups?mostPopular=&gid=2901 Get alerts to jobs like this, to your inbox. Create Job Alert Similar Jobs You May Like See More JobsSee All Suggested searches";
        StringTools stringTools = new StringTools();
        String  actual = stringTools.removeEverythingAfter(string, "days ago");
        String expected = "View All num of num Close (Esc) Entry Level - Software Engineer I 3.9 Relevante – San Carlos, CA 5 days ago";
        assertEquals(expected,actual);
    }

    @Test
    public void removeEverythingAfterAndIncludingTerm(){
        String blah = "Experience with one of the world's most largest and most reputable companies in the US</li>";
        StringTools stringTools = new StringTools();
        String  actual = stringTools.removeEverythingAfterAndIncludingTerm(blah, "</li>");
        String expected = "Experience with one of the world's most largest and most reputable companies in the US";
        assertEquals(expected,actual);
    }
}